name: deploy-chabokan
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: update-chabokan
        env:
          CHABOKAN_TOKEN: ${{ secrets.4e42b3c5a991aa2ab632cb23cc9a38a5a596136a }}
        run: |
          npm install -g @chabokan.net/cli
          chabok login -t $CHABOKAN_TOKEN
          chabok deploy -s panel-supportweb
